/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: auth_config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "auth_config.pb-c.h"
void   auth_config_request__init
                     (AuthConfigRequest         *message)
{
  static const AuthConfigRequest init_value = AUTH_CONFIG_REQUEST__INIT;
  *message = init_value;
}
size_t auth_config_request__get_packed_size
                     (const AuthConfigRequest *message)
{
  assert(message->base.descriptor == &auth_config_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth_config_request__pack
                     (const AuthConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth_config_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth_config_request__pack_to_buffer
                     (const AuthConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth_config_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthConfigRequest *
       auth_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthConfigRequest *)
     protobuf_c_message_unpack (&auth_config_request__descriptor,
                                allocator, len, data);
}
void   auth_config_request__free_unpacked
                     (AuthConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &auth_config_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   auth_config_response__init
                     (AuthConfigResponse         *message)
{
  static const AuthConfigResponse init_value = AUTH_CONFIG_RESPONSE__INIT;
  *message = init_value;
}
size_t auth_config_response__get_packed_size
                     (const AuthConfigResponse *message)
{
  assert(message->base.descriptor == &auth_config_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth_config_response__pack
                     (const AuthConfigResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth_config_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth_config_response__pack_to_buffer
                     (const AuthConfigResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth_config_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthConfigResponse *
       auth_config_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthConfigResponse *)
     protobuf_c_message_unpack (&auth_config_response__descriptor,
                                allocator, len, data);
}
void   auth_config_response__free_unpacked
                     (AuthConfigResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &auth_config_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor auth_config_request__field_descriptors[2] =
{
  {
    "endpoint",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthConfigRequest, endpoint),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthConfigRequest, token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth_config_request__field_indices_by_name[] = {
  0,   /* field[0] = endpoint */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange auth_config_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor auth_config_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AuthConfigRequest",
  "AuthConfigRequest",
  "AuthConfigRequest",
  "",
  sizeof(AuthConfigRequest),
  2,
  auth_config_request__field_descriptors,
  auth_config_request__field_indices_by_name,
  1,  auth_config_request__number_ranges,
  (ProtobufCMessageInit) auth_config_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor auth_config_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AuthConfigResponse, status),
    &auth_config_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthConfigResponse, deviceid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth_config_response__field_indices_by_name[] = {
  1,   /* field[1] = deviceId */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange auth_config_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor auth_config_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AuthConfigResponse",
  "AuthConfigResponse",
  "AuthConfigResponse",
  "",
  sizeof(AuthConfigResponse),
  2,
  auth_config_response__field_descriptors,
  auth_config_response__field_indices_by_name,
  1,  auth_config_response__number_ranges,
  (ProtobufCMessageInit) auth_config_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue auth_config_status__enum_values_by_number[2] =
{
  { "ConfigSuccess", "AUTH_CONFIG_STATUS__ConfigSuccess", 0 },
  { "ConfigFail", "AUTH_CONFIG_STATUS__ConfigFail", 1 },
};
static const ProtobufCIntRange auth_config_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex auth_config_status__enum_values_by_name[2] =
{
  { "ConfigFail", 1 },
  { "ConfigSuccess", 0 },
};
const ProtobufCEnumDescriptor auth_config_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AuthConfigStatus",
  "AuthConfigStatus",
  "AuthConfigStatus",
  "",
  2,
  auth_config_status__enum_values_by_number,
  2,
  auth_config_status__enum_values_by_name,
  1,
  auth_config_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
